export const products = [
  {
    id: "1",
    title: "The Iconic Mesh Polo Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate4?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate17?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 95,
    colors: ["white", "black", "blue", "red"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
    arrivals: "Gear Up",
  },
  {
    id: "2",
    title: "Mesh Long-Sleeve Polo Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["navy", "gray", "white", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "men",
    arrivals: "Gear Up",
  },
  {
    id: "3",
    title: "Soft Cotton Polo Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate4?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate5?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["red", "black", "green", "teal"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
    arrivals: "Gear Up",
  },
  {
    id: "4",
    title: "Custom Slim Fit Big Pony Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 115,
    colors: ["gray", "red", "black", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
    arrivals: "Gear Up",
  },
  {
    id: "5",
    title: "Original Fit Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 168,
    colors: ["navy", "green", "yellow", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "6",
    title: "Custom Slim Fit Stretch Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 98,
    colors: ["gray", "black", "blue", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
    arrivals: "New Arrivals",
  },
  {
    id: "7",
    title: "Classic Fit Cotton-Linen Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["white", "red", "lightblue", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
    arrivals: "New Arrivals",
  },
  {
    id: "8",
    title: "RLX CLARUS Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate4?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate5?$rl_df_pdp_5_7$",
    description: "RLX",
    content:
      "Ralph Lauren is proud to debut the RLX CLARUS® Polo Shirt—the first shirt of its kind made with CLARUS®, a textile innovation from Natural Fiber Welding, Inc. (NFW), that transforms our Polo shirt's natural cotton fibers into a breathable, high-performance fabric with moisture management and quick-drying attributes similar to plastic-based synthetic fabrics like polyester and nylon. Ralph Lauren is proud to partner with NFW as we continue our commitment to a more sustainable and equitable future.",
    price: 168,
    colors: ["white", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "9",
    title: "The Iconic Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["white", "black", "gray", "green"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
    arrivals: "New Arrivals",
  },
  {
    id: "10",
    title: "Soft Cotton Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 115,
    colors: ["lightgreen", "orange", "lightgray", "ligtblue"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "11",
    title: "Performance Jersey Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["lightblue", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "12",
    title: "Mesh Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 125,
    colors: ["gray", "black", "navy"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "men",
  },
  {
    id: "13",
    title: "Soft Cotton Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 90,
    colors: ["navy", "brown", "lightblue", "burlywood"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "men",
  },
  {
    id: "14",
    title: "Polo Bear Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 125,
    colors: ["navy", "lightblue"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "15",
    title: "Custom Slim Fit Polo Bear Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 425,
    colors: ["black", "red"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "16",
    title: "Washed Piqué Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 395,
    colors: ["gray", "white"],
    size: ["L", "M"],
    sleeve: "Long Sleeve",
    category: "men",
  },
  {
    id: "17",
    title: "Custom Slim Fit Piqué Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 395,
    colors: ["gray", "white"],
    size: ["L", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "18",
    title: "Terry Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 295,
    colors: ["blue", "black", "white"],
    size: ["L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "19",
    title: "Classic Fit Performance Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_alternate4?$rl_df_pdp_5_7$",
    description: "RLX Golf",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 115,
    colors: ["lightblue", "white"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "20",
    title: "Classic Fit Performance Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_alternate4?$rl_df_pdp_5_7$",
    description: "RLX Golf",
    content:
      "This striped Polo shirt features moisture-wicking properties to help keep you cool and comfortable on the course. Its lightweight, breathable stretch jersey is crafted with recycled polyester, reducing our dependence on virgin petroleum-based material.",
    price: 110,
    colors: ["pink", "black"],
    size: ["L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "21",
    title: "Classic Fit Performance Print Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_alternate4?$rl_df_pdp_5_7$",
    description: "RLX Golf",
    content:
      "This striped Polo shirt features moisture-wicking properties to help keep you cool and comfortable on the course. Its lightweight, breathable stretch jersey is crafted with recycled polyester, reducing our dependence on virgin petroleum-based material.",
    price: 115,
    colors: ["black", "red"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "22",
    title: "Wool Piqué Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 495,
    colors: ["black", "red"],
    size: ["XL", "M"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "23",
    title: "Custom Slim Fit Polo Bear Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 425,
    colors: ["black", "red"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "24",
    title: "The Iconic Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate2?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate5?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "A Ralph Lauren icon, this Polo shirt is crafted from comfortable cotton mesh and finished with our signature embroidered Pony.",
    price: 45,
    colors: ["pink", "green", "blue", "yellow", "white", "gray", "black"],
    size: ["XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
    arrivals: "New Arrivals",
  },
  {
    id: "25",
    title: "The Earth Polo",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1441708_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1441708_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "Designed with Mother Nature in mind, The Earth Polo is crafted from an innovative fabric made entirely from plastic bottles and dyed using a waterless process. To learn more about The Earth Polo and Ralph Lauren's sustainability initiatives, including our global commitment to using 170 million recycled plastic bottles in our products and packaging by 2025, please visit RalphLauren.com/earthpolo.",
    price: 45,
    colors: ["green", "red", "blue", "white"],
    size: ["M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "26",
    title: "Big Pony Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_alternate2?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_alternate4?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "This wear-with-anything Polo shirt is finished with our signature Big Pony and a '3' patch, representing the number worn by a polo team's strongest player.",
    price: 49,
    colors: ["white", "gray", "red", "yellow"],
    size: ["M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
    arrivals: "New Arrivals",
  },
  {
    id: "27",
    title: "Performance Jersey Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1251136_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1251136_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "Made from moisture-wicking stretch jersey, this Polo shirt will keep him comfortable during class and practice.",
    price: 45,
    colors: ["navy", "red", "blue", "black", "white"],
    size: ["S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "28",
    title: "Performance Stretch Jersey Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1456632_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1456632_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "This Polo shirt's moisture-wicking fabric is crafted with recycled polyester, reinforcing Ralph Lauren's aim to create the highest-quality products with minimal harm to the environment.",
    price: 45,
    colors: ["green", "red"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
    arrivals: "New Arrivals",
  },
  {
    id: "29",
    title: "Cotton Mesh Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1456390_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1456390_alternate1?$rl_df_pdp_5_7$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate2?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate5?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "This classic Polo shirt is made from easy-to-care-for cotton mesh and finished with our signature embroidered Pony.",
    price: 50,
    colors: ["yellow", "orange", "green", "blue"],
    size: ["M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "kids",
  },
  {
    id: "30",
    title: "Long-Sleeve Uniform Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1122879_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1122879_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "Combining breathable cotton mesh and our signature embroidered Pony, this classic Polo shirt is a back-to-school essential.",
    price: 45,
    colors: ["white", "black"],
    size: ["L", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "kids",
    arrivals: "Gear Up",
  },
  {
    id: "31",
    title: "Cotton Mesh Uniform Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1122878_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1122878_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "Essential for school uniforms, this classic polo shirt is crafted from soft cotton mesh and features our tonal signature embroidered pony at the left hem.",
    price: 39,
    colors: ["navy", "white"],
    size: ["M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
    arrivals: "Gear Up",
  },
  {
    id: "32",
    title: "US Open Ball Crew Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455643_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455643_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "Part of our 2022 US Open Tennis Championships collection, this Polo shirt is inspired by the tournament's official men's ball crew uniform, which was designed exclusively by Polo Ralph Lauren.",
    price: 85,
    colors: ["green", "white"],
    size: ["L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "33",
    title: "Big Pony Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455505_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455505_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "Finished with our iconic Big Pony, this Polo shirt features bold color-blocking in the season's vibrant shades.",
    price: 59,
    colors: ["green", "white"],
    size: ["L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "34",
    title: "Big Pony Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1417656_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1417656_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "Finished with our iconic Big Pony, this Polo shirt features bold color-blocking in the season's vibrant shades.",
    price: 80,
    colors: ["gray", "white", "navy"],
    size: ["L", "S"],
    sleeve: "Long Sleeve",
    category: "kids",
  },
  {
    id: "35",
    title: "Striped Mesh Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455583_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455583_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "Rich-hued stripes and washed cotton mesh ensure this Polo shirt will be in regular rotation through the cooler months.",
    price: 60,
    colors: ["green", "white"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Long Sleeve",
    category: "kids",
  },
  {
    id: "36",
    title: "Striped Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455570_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455570_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "This Polo shirt features five striped patterns and a pennant-inspired '1967' detail at the front.",
    price: 69,
    colors: ["green", "yellow", "red"],
    size: ["L", "M"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "37",
    title: "Color-Blocked Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455569_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455569_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "In breathable cotton mesh, this Polo shirt features bold color-blocking and three iterations of our signature embroidered Pony.",
    price: 55,
    colors: ["navy", "yellow"],
    size: ["XL", "M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "38",
    title: "Tie-Dye Ombré Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439600_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439600_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "This Polo shirt achieves its vibrant ombré motif through a multilevel dye process and hand detailing.",
    price: 55,
    colors: ["blue", "white", "orange"],
    size: ["L", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "39",
    title: "Sailboat Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439618_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439618_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "In our signature mesh fabric, this Polo shirt features a nautical-inspired print of sailboats and palm trees.",
    price: 55,
    colors: ["blue", "red"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "40",
    title: "Print Cotton Jersey Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439541_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439541_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "In soft cotton jersey, this Polo shirt features a resort-inspired print of palm trees, tennis rackets, and bicycles.",
    price: 55,
    colors: ["black", "white"],
    size: ["L", "M"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "41",
    title: "Knit Double-Breasted Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1296670_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1296670_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1296670_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1296670_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1296670_alternate5?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "The structure of a double-breasted blazer meets the drape of a sweater in this cotton-blend jacket.",
    price: 398,
    colors: ["navy", "black"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Long Sleeve",
    category: "women",
    arrivals: "New Arrivals",
  },
  {
    id: "42",
    title: "Houndstooth-Trim Plaid Tweed Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453048_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453048_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453048_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453048_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453048_alternate5?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "Tapered at the waist and slightly flared to the hem, this tailored blazer merges traditional menswear-inspired Italian tweed with a romantic silhouette and Polo's subtle pattern play, featuring houndstooth framing.",
    price: 598,
    colors: ["brown", "black"],
    size: ["L", "M"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "43",
    title: "Patchwork Tweed Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453049_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453049_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453049_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453049_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453049_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "Expertly tailored in Italy from a medley of herringbone, plaid, and houndstooth patches, this tweed blazer draws inspiration from Polo's rich heritage and propensity to playfully mix patterns.",
    price: 998,
    colors: ["brown", "black", "blue"],
    size: ["M", "S"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "44",
    title: "Wool-Blend Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453148_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453148_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453148_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453148_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "Crafted from a soft wool blend, this sleek blazer is embellished with signature crest-embossed buttons for a heritage feel.",
    price: 498,
    colors: ["navy", "black"],
    size: ["XL", "M", "S"],
    sleeve: "Long Sleeve",
    category: "women",
    arrivals: "New Arrivals",
  },
  {
    id: "45",
    title: "Pinstripe Cotton-Linen-Wool Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446194_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446194_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446194_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446194_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446194_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "Tailored from a blend of Italian cotton, linen, and wool, this relaxed-fitting blazer is partially lined for a light weight and features a pinstripe motif.",
    price: 598,
    colors: ["white", "gray", "black"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "46",
    title: "Plaid Wool-Blend Tweed Hacking Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446192_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446192_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446192_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446192_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446192_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "The structure of a double-breasted blazer meets the drape of a sweater in this cotton-blend jacket.",
    price: 598,
    colors: ["brown", "white", "black"],
    size: ["L", "XS"],
    sleeve: "Long Sleeve",
    category: "women",
    arrivals: "New Arrivals",
  },
  {
    id: "47",
    title: "Herringbone Silk-Blend Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1351921_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1351921_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1351921_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1351921_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1351921_alternate5?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "Designed with a single-breasted silhouette and featuring a timeless herringbone pattern, this tailored blazer is cut from a luxe blend of Italian-spun yarn and is enhanced with supple lamb-suede accents.",
    price: 498,
    colors: ["brown", "black"],
    size: ["L", "M", "S"],
    sleeve: "Long Sleeve",
    category: "women",
    arrivals: "Gear Up",
  },
  {
    id: "48",
    title: "Chambray Cotton Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446199_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446199_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446199_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446199_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1446199_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "This double-breasted cotton blazer is expertly tailored for a slim fit and garment-dyed for greater depth of color. Its partial lining ensures a light weight and breathability.",
    price: 455,
    colors: ["lightblue", "white"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "women",
    arrivals: "Gear Up",
  },
  {
    id: "49",
    title: "Hybrid Funnelneck Sweater Jacket",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453223_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453223_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453223_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453223_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453223_alternate4?$rl_df_pdp_5_7$",
    description: "RLX",
    content:
      "A lightly filled taffeta front panel adds channel-quilted woven texture to this full-zip sweater jacket, which is crafted using worsted wool and outfitted with thumbholes.",
    price: 398,
    colors: ["orange", "white"],
    size: ["M", "XS"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "50",
    title: "Hybrid High-Pile & Ripstop-Panel Jacket",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453232_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453232_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453232_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453232_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453232_alternate4?$rl_df_pdp_5_7$",
    description: "RLX",
    content:
      "Designed for an oversize fit, this jacket merges soft high-pile fleece with woven ripstop panels and onion quilting. Our signature 'RLX' logo accents the left chest zip pocket.",
    price: 445,
    colors: ["white", "gray"],
    size: ["M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "51",
    title: "Ruana Double-Faced Merino-Silk Sweater",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1447841_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1447841_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1447841_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1447841_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1447841_alternate4?$rl_df_pdp_5_7$",
    description: "Ralph Lauren Collection",
    content:
      "The Ruana sweater is Ralph Lauren's most luxurious interpretation of vintage woven blankets. Rendered from a rich combination of merino wool and mulberry silk, this season's iteration is designed with a reversible, double-faced silhouette, with one side showcasing a matte finish, and the other displaying high-shine silk yarn. Its Italian-made, two-tone design is trimmed with bold blanket stripes, nodding to the striking black-and-white décor of a New York City penthouse apartment.",
    price: 865,
    colors: ["gray", "black"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "52",
    title: "Donaldson Checked Tweed Jacket",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1460713_alternate1?$rl_df_pdp_5_7$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1460713_alternate3?$rl_df_pdp_5_7$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1460713_alternate4?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1460713_alternate5?$rl_df_pdp_5_7$",
    description: "Ralph Lauren Collection",
    content:
      "Inspired by a Ralph Lauren Collection Spring 2010 jacket, the Donaldson is made from the season's exclusive checked wool-blend tweed, sourced from a heritage Irish mill and specially selected for its soft hand. Designed with a slim silhouette, this jacket is tailored with traditional suiting elements, including peak lapels, shoulder pads, flapped pockets, and a double-breasted silhouette detailed with genuine horn buttons engraved with 'Ralph Lauren.'",
    price: 665,
    colors: ["brown", "white"],
    size: ["L", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "53",
    title: "Parker Checked Plaid Tweed Jacket",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1460706_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1460706_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1460706_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1460706_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1460706_alternate4?$rl_df_pdp_5_7$",
    description: "Ralph Lauren Collection",
    content:
      "Designed with hacking pockets, a detail often found on traditional English riding attire, the Parker jacket channels Ralph Lauren's iconic equestrian-inspired heritage. American-made, it's beautifully constructed with a bevy of highly considered details, including slimming waist darts, notch lapels, and a single-breasted closure that secures with a genuine horn button engraved with 'Ralph Lauren.' Wool-blend checked tweed, sourced from a heritage Irish mill, is specially selected for its remarkable drape and soft hand.",
    price: 880,
    colors: ["brown", "black"],
    size: ["L", "S"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "54",
    title: "Herringbone Tweed Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453346_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453346_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453346_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453346_alternate4?$rl_df_pdp_5_7$",
    description: "RLX",
    content:
      "Designed with traditional tailoring elements, like crisp waist darts and shoulder pads, this smart blazer is crafted from herringbone tweed for added texture and a sophisticated sensibility. Signature engraved horn-effect buttons offer an iconic Lauren Ralph Lauren finish.",
    price: 345,
    colors: ["brown", "black"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "55",
    title: "Bullion Corduroy Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453356_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453356_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453356_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453356_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1453356_alternate4?$rl_df_pdp_5_7$",
    description: "RLX",
    content:
      "This soft corduroy blazer embodies luxurious Lauren style with a signature bullion patch at the chest and horn-effect buttons.",
    price: 245,
    colors: ["orange", "white", "black"],
    size: ["M", "S"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "56",
    title: "Pinstripe Wool Crepe Blazer",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452769_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452769_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452769_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452769_alternate4?$rl_df_pdp_5_7$",
    description: "RLX",
    content:
      "An enduring wardrobe staple, this sophisticated blazer is distinguished by classic pinstripes. Woven from luxurious merino wool crepe, menswear-inspired notch lapels provide a refined finish.",
    price: 295,
    colors: ["black", "navy", "gray"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "women",
  },
  {
    id: "57",
    title: "The Upcycled Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1462932_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1462932_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1462932_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1462932_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1462932_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "In collaboration with Atelier & Repairs, Polo Ralph Lauren has created The Upcycled Polo Shirt to save hundreds of garments from going to waste. Vintage Polo shirts with life left to live were gathered, deeply cleaned, and then carefully renewed by hand—repaired, reinforced, detailed, and then garment-dyed with pure natural indigo. The shirts may be from decades past, but the renewed result is something entirely new. No two look exactly alike.",
    priceFrom: 198,
    price: 129,
    colors: ["blue", "navy", "gray"],
    size: ["XXL", "XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "sale",
  },
  {
    id: "58",
    title: "Knit Oxford Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435894_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435894_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435894_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435894_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435894_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "In collaboration with Atelier & Repairs, Polo Ralph Lauren has created The Upcycled Polo Shirt to save hundreds of garments from going to waste. Vintage Polo shirts with life left to live were gathered, deeply cleaned, and then carefully renewed by hand—repaired, reinforced, detailed, and then garment-dyed with pure natural indigo. The shirts may be from decades past, but the renewed result is something entirely new. No two look exactly alike.",
    priceFrom: 110,
    price: 80,
    colors: ["white", "black"],
    size: ["XL", "L", "S"],
    sleeve: "Long Sleeve",
    category: "sale",
  },
  {
    id: "59",
    title: "The Iconic Oxford Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-305177_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-305177_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-305177_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-305177_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-305177_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "In collaboration with Atelier & Repairs, Polo Ralph Lauren has created The Upcycled Polo Shirt to save hundreds of garments from going to waste. Vintage Polo shirts with life left to live were gathered, deeply cleaned, and then carefully renewed by hand—repaired, reinforced, detailed, and then garment-dyed with pure natural indigo. The shirts may be from decades past, but the renewed result is something entirely new. No two look exactly alike.",
    priceFrom: 99,
    price: 59,
    colors: ["white", "lightblue", "pink"],
    size: ["L", "M", "S"],
    sleeve: "Long Sleeve",
    category: "sale",
  },
  {
    id: "60",
    title: "Soft Cotton Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266719_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266719_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266719_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266719_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266719_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from luxe cotton interlock with an ultrasoft finish.",
    priceFrom: 110,
    price: 70,
    colors: ["navy", "white", "gray", "green", "blue"],
    size: ["XXL", "L", "M"],
    sleeve: "Short Sleeve",
    category: "sale",
  },
  {
    id: "61",
    title: "The RL Fleece Rugby Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397810_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397810_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397810_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397810_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397810_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "This cotton-blend piece combines the look of our iconic rugby shirt with the warmth of our signature RL Fleece.",
    priceFrom: 125,
    price: 90,
    colors: ["navy", "black", "gray"],
    size: ["XXL", "L", "M", "S"],
    sleeve: "Long Sleeve",
    category: "sale",
  },
  {
    id: "62",
    title: "Bomber Jacket",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452396_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452396_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452396_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452396_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452396_alternate4?$rl_df_pdp_5_7$",
    description: "Lauren Petite",
    content:
      "This iconic bomber jacket stays true to authentic styling with utility-inspired details, like snapped shoulder epaulets, exposed zippers, and rib-knit trim. Lauren's signature monogram at the hip offers a timeless finish.",
    priceFrom: 265,
    price: 199,
    colors: ["green", "black", "red"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "sale",
  },
  {
    id: "63",
    title: "Belted Twill Field Jacket",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452423_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452423_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452423_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1452423_alternate4?$rl_df_pdp_5_7$",
    description: "Lauren Petite",
    content:
      "Cut from crisp twill for a polished look, this field jacket is distinguished by utilitarian-inspired details, like buttoned-flap patch pockets and buttoned shoulder epaulets. Embellished with signature horn-effect buttons for a heritage-inspired finish, it includes a buckled self-belt that accentuates the waist and offers added sophistication.",
    priceFrom: 305,
    price: 225,
    colors: ["green", "white", "orange"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Long Sleeve",
    category: "sale",
  },
  {
    id: "64",
    title: "The Iconic Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1374583_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1374583_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1374583_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1374583_alternate2?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1374583_alternate3?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "A Ralph Lauren icon, this Polo shirt is crafted from comfortable cotton mesh and finished with our signature embroidered Pony.",
    priceFrom: 49,
    price: 16,
    colors: [
      "green",
      "white",
      "lightblue",
      "blue",
      "red",
      "yellow",
      "orange",
      "black",
    ],
    size: ["L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "sale",
  },
  {
    id: "65",
    title: "Linen Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439061_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439061_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439061_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439061_alternate2?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439061_alternate4?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "A Ralph Lauren icon, this Polo shirt is crafted from comfortable cotton mesh and finished with our signature embroidered Pony.",
    priceFrom: 55,
    price: 25,
    colors: ["red", "white"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "sale",
  },
  {
    id: "66",
    title: "Color-Blocked Logo Cotton Tee",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1440584_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1440584_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1440584_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1440584_alternate2?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1440584_alternate4?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "A Ralph Lauren icon, this Polo shirt is crafted from comfortable cotton mesh and finished with our signature embroidered Pony.",
    priceFrom: 49,
    price: 16,
    colors: ["blue", "white", "lightblue"],
    size: ["S", "XS"],
    sleeve: "Short Sleeve",
    category: "sale",
  },
  {
    id: "67",
    title: "Striped Cotton Hooded Tee",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439549_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439549_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "This hooded tee unites soft cotton jersey with colorful stripes and our signature embroidered Pony. Ralph Lauren partners with Better Cotton™ to improve cotton farming globally. Better Cotton trains farmers to use water efficiently, care for the health of the soil and natural habitats, reduce use of the most harmful chemicals, and implement the principles of decent work.",
    priceFrom: 39,
    price: 19,
    colors: ["white", "green", "red", "yellow", "orange"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "sale",
  },
  {
    id: "68",
    title: "Logo Double-Knit Hoodie",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1441699_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1441699_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "Made from a soft cotton blend, this hoodie features a color-blocked design that complements a bold, multihued logo. Ralph Lauren partners with Better Cotton™ to improve cotton farming globally. Better Cotton trains farmers to use water efficiently, care for the health of the soil and natural habitats, reduce use of the most harmful chemicals, and implement the principles of decent work.",
    priceFrom: 69,
    price: 24,
    colors: ["blue", "green", "red"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "sale",
  },
];
